# mSwali PWA CI/CD
image: mSwali PWA

pipelines:
  default:
    - parallel:
        - step:
            name: "Build and Test"
            script:
              - echo "Your build and test goes here..."
        - step:
            name: "Lint"
            script:
              - echo "Your linting goes here..."
        - step:
            name: "Security scan"
            script:
              - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: "Deployment to Main Branch"
        deployment: main
        trigger: "manual"
        script:
          - echo "Your deployment to staging script goes here..."
          - git push origin main -f
    - step:
        name: "Deployment to Production"
        deployment: production
        trigger: "manual"
        script:
          - echo "Your deployment to production script goes here..."
